"""
╔══════════════════════════════════════════════════════════════╗
║          QUIZFORGE  pdf_generator.py  v1.0                  ║
║          fpdf2 · Chapter-wise PDF · TOC · Answer Key        ║
╚══════════════════════════════════════════════════════════════╝

Usage (standalone):
    pip install fpdf2
    python pdf_generator.py --exam JEE --input pyq_full_database.json

Usage (from Flask):
    from pdf_generator import generate_pdf
    path = generate_pdf(questions, exam="JEE", output_dir="/tmp/quizforge")

Generated PDF structure:
  Page 1   — Cover (exam name, date, question count)
  Page 2   — Table of Contents (auto-built, with page numbers)
  Pages 3+ — Questions grouped by chapter
             MCQ options printed A–D
             Numerical: blank answer box
  Last 2p  — Answer Key (chapter-wise, two-column table)

24-hour cache:
  The cache key is SHA-256(exam + sorted question IDs).
  PDFs are stored in output_dir and reused for 24 h.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import time
from collections import defaultdict
from typing import Optional

try:
    from fpdf import FPDF, XPos, YPos
    _FPDF_OK = True
except ImportError:
    _FPDF_OK = False

# ═══════════════════════════════════════════════════════════════
# COLOURS  (RGB)
# ═══════════════════════════════════════════════════════════════

C_NAVY   = (13,  29,  82)
C_BLUE   = (30,  58, 138)
C_ORANGE = (234, 88,  12)
C_CREAM  = (250, 246, 239)
C_WHITE  = (255, 255, 255)
C_GREY   = (120, 113, 108)
C_DARK   = (28,  25,  23)
C_GREEN  = (21, 128,  61)
C_RED    = (185, 28,  28)

EXAM_COLOURS: dict[str, tuple] = {
    "JEE":  C_BLUE,
    "NEET": C_GREEN,
    "UPSC": C_RED,
    "CAT":  (180, 83, 9),
    "SAT":  (109, 40, 217),
    "GK":   C_ORANGE,
    "ALL":  C_NAVY,
}

CACHE_TTL = 86_400   # 24 hours in seconds


# ═══════════════════════════════════════════════════════════════
# CACHE HELPERS
# ═══════════════════════════════════════════════════════════════

def _cache_key(questions: list[dict], exam: str) -> str:
    ids = sorted(str(q.get("id", q.get("question", "")[:40])) for q in questions)
    raw = exam + "|" + ",".join(ids)
    return hashlib.sha256(raw.encode()).hexdigest()[:16]


def _cached_path(output_dir: str, key: str) -> Optional[str]:
    """Return path if a valid (non-expired) cached PDF exists, else None."""
    path = os.path.join(output_dir, f"quizforge_{key}.pdf")
    if os.path.exists(path):
        age = time.time() - os.path.getmtime(path)
        if age < CACHE_TTL:
            return path
    return None


# ═══════════════════════════════════════════════════════════════
# PDF CLASS
# ═══════════════════════════════════════════════════════════════

class QuizForgePDF(FPDF):
    """Extended FPDF with branded header/footer and helper methods."""

    def __init__(self, exam: str = "ALL"):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.exam        = exam
        self.accent      = EXAM_COLOURS.get(exam, C_NAVY)
        self.set_margins(20, 20, 20)
        self.set_auto_page_break(auto=True, margin=25)
        self._toc_entries: list[tuple[str, int]] = []   # (chapter, page_no)
        self._answer_key:  list[tuple[int, str, str]] = []  # (q_num, answer, exam)

    # ── Header ───────────────────────────────────────────────
    def header(self):
        if self.page_no() <= 2:
            return
        self.set_fill_color(*self.accent)
        self.rect(0, 0, 210, 8, style="F")
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*C_WHITE)
        self.set_xy(0, 1)
        self.cell(0, 6, f"  QuizForge — {self.exam} Question Bank", align="L")
        self.set_text_color(*C_DARK)

    # ── Footer ───────────────────────────────────────────────
    def footer(self):
        if self.page_no() <= 2:
            return
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*C_GREY)
        self.cell(0, 5, f"Page {self.page_no()} | quizforge.app | Generated by QuizForge v3.0", align="C")
        self.set_text_color(*C_DARK)

    # ── Coloured section label ────────────────────────────────
    def section_label(self, text: str, color: tuple = None):
        c = color or self.accent
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*c)
        self.cell(0, 5, text.upper(), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_draw_color(*c)
        self.set_line_width(0.4)
        self.line(self.get_x(), self.get_y(), self.get_x() + 170, self.get_y())
        self.ln(2)
        self.set_text_color(*C_DARK)
        self.set_draw_color(0, 0, 0)

    # ── Chapter heading ──────────────────────────────────────
    def chapter_heading(self, chapter: str, page_hint: int):
        self._toc_entries.append((chapter, self.page_no()))
        self.set_fill_color(*self.accent)
        self.set_text_color(*C_WHITE)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, f"  {chapter}", fill=True,
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(3)
        self.set_text_color(*C_DARK)

    # ── Difficulty badge ─────────────────────────────────────
    def _diff_color(self, diff: str) -> tuple:
        return {"Easy": C_GREEN, "Medium": (180, 83, 9), "Hard": C_RED}.get(diff, C_GREY)

    # ── Single MCQ question ───────────────────────────────────
    def render_mcq(self, q_num: int, q: dict):
        diff_col = self._diff_color(q.get("difficulty", "Medium"))

        # Question number + metadata row
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*self.accent)
        self.cell(10, 5, f"Q{q_num}.", new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*diff_col)
        self.cell(25, 5, q.get("difficulty", "Medium"), new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_text_color(*C_GREY)
        marks = q.get("marks", 1)
        neg   = q.get("negative_marks", 0)
        self.cell(0, 5, f"[+{marks} / {neg}]  {q.get('year','Practice')}",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Question text
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*C_DARK)
        self.set_x(10)
        self.multi_cell(0, 5, q.get("question", ""), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(1)

        # Options
        opts = q.get("options") or {}
        for letter, text in opts.items():
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(*self.accent)
            self.set_x(14)
            self.cell(8, 5, f"({letter})", new_x=XPos.RIGHT, new_y=YPos.TOP)
            self.set_font("Helvetica", "", 9)
            self.set_text_color(*C_DARK)
            self.multi_cell(0, 5, str(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Record answer
        self._answer_key.append((q_num, q.get("answer", "?"), q.get("exam", "")))
        self.ln(4)

    # ── Single Numerical question ─────────────────────────────
    def render_numerical(self, q_num: int, q: dict):
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*C_BLUE)
        self.cell(10, 5, f"Q{q_num}.", new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(109, 40, 217)
        self.cell(30, 5, "[NUMERICAL]", new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_text_color(*C_GREY)
        marks = q.get("marks", 4)
        self.cell(0, 5, f"[+{marks} / 0]  {q.get('year','Practice')}",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        self.set_font("Helvetica", "", 10)
        self.set_text_color(*C_DARK)
        self.set_x(10)
        self.multi_cell(0, 5, q.get("question", ""), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Answer box
        self.ln(1)
        self.set_x(14)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*C_GREY)
        self.cell(30, 5, "Answer:", new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_draw_color(*C_GREY)
        self.rect(self.get_x(), self.get_y(), 50, 8)
        if q.get("unit"):
            self.set_x(self.get_x() + 53)
            self.cell(20, 8, q["unit"])

        answer_str = str(q.get("answer") or q.get("numericalAnswer", ""))
        self._answer_key.append((q_num, answer_str, q.get("exam", "")))
        self.ln(12)

    # ── Cover page ───────────────────────────────────────────
    def cover_page(self, exam: str, question_count: int, generated: str):
        self.add_page()
        # Full-bleed accent bar
        self.set_fill_color(*self.accent)
        self.rect(0, 0, 210, 80, style="F")

        # Logo area
        self.set_font("Helvetica", "B", 38)
        self.set_text_color(*C_WHITE)
        self.set_xy(20, 22)
        self.cell(0, 15, "QuizForge", align="L")
        self.set_font("Helvetica", "", 13)
        self.set_xy(20, 40)
        self.cell(0, 8, "Premium PYQ Engine  ·  v3.0", align="L")

        # Exam tag
        self.set_font("Helvetica", "B", 22)
        self.set_xy(20, 55)
        self.cell(0, 10, f"{exam}  Question Bank", align="L")

        # Stats
        self.set_text_color(*C_DARK)
        self.set_font("Helvetica", "", 11)
        self.set_xy(20, 100)
        self.cell(0, 8, f"Total Questions : {question_count}")
        self.set_xy(20, 110)
        self.cell(0, 8, f"Generated       : {generated}")
        self.set_xy(20, 120)
        self.cell(0, 8, "Source          : OpenTDB · IndiaBix · JEE/NEET Archive")

        # Disclaimer
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*C_GREY)
        self.set_xy(20, 260)
        self.multi_cell(0, 5,
            "This question bank is compiled for practice purposes. "
            "Actual exam questions may vary. Always refer to official sources.")

    # ── TOC page ─────────────────────────────────────────────
    def toc_page(self):
        self.add_page()
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(*self.accent)
        self.cell(0, 12, "Table of Contents", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_draw_color(*self.accent)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(4)

        self.set_font("Helvetica", "", 10)
        self.set_text_color(*C_DARK)
        for chapter, pg in self._toc_entries:
            self.cell(150, 6, chapter, new_x=XPos.RIGHT, new_y=YPos.TOP)
            self.cell(20, 6, str(pg), align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.set_draw_color(*C_GREY)
            self.set_line_width(0.1)
            # Dotted line (drawn as many small segments)
            x1, y = 20 + self.get_string_width(chapter) + 2, self.get_y() - 3
            x2 = 188 - self.get_string_width(str(pg)) - 2
            dots = int((x2 - x1) / 2)
            for d in range(dots):
                self.set_xy(x1 + d * 2, y)
                self.cell(1, 0, ".")

    # ── Answer key ───────────────────────────────────────────
    def answer_key_page(self):
        self.add_page()
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*self.accent)
        self.cell(0, 10, "Answer Key", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_draw_color(*self.accent)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(4)

        # Two-column table
        col_w  = 82
        row_h  = 6
        per_col = 45   # answers per column

        col1 = self._answer_key[:per_col]
        col2 = self._answer_key[per_col:per_col * 2]

        for i in range(max(len(col1), len(col2))):
            # Left column
            if i < len(col1):
                q_num, ans, _ = col1[i]
                self.set_font("Helvetica", "B", 8)
                self.set_text_color(*C_GREY)
                self.set_x(20)
                self.cell(12, row_h, f"Q{q_num}.", new_x=XPos.RIGHT, new_y=YPos.TOP)
                self.set_font("Helvetica", "B", 9)
                self.set_text_color(*self.accent)
                self.cell(col_w - 12, row_h, ans, new_x=XPos.RIGHT, new_y=YPos.TOP)
            else:
                self.set_x(20 + col_w)

            # Right column
            if i < len(col2):
                q_num, ans, _ = col2[i]
                self.set_font("Helvetica", "B", 8)
                self.set_text_color(*C_GREY)
                self.cell(12, row_h, f"Q{q_num}.", new_x=XPos.RIGHT, new_y=YPos.TOP)
                self.set_font("Helvetica", "B", 9)
                self.set_text_color(*self.accent)
                self.cell(col_w - 12, row_h, ans, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            else:
                self.ln(row_h)


# ═══════════════════════════════════════════════════════════════
# PUBLIC API
# ═══════════════════════════════════════════════════════════════

def generate_pdf(
    questions: list[dict],
    exam: str = "ALL",
    output_dir: str = ".",
    use_cache: bool = True,
) -> str:
    """
    Build a chapter-wise PDF for the given question list.

    Args:
        questions:  List of question dicts (QuizForge schema).
        exam:       Exam label used in title / branding.
        output_dir: Directory to write the PDF.
        use_cache:  If True, return an existing file if <24h old.

    Returns:
        Absolute path to the generated PDF.

    Raises:
        ImportError: if fpdf2 is not installed.
        RuntimeError: if the PDF cannot be written.
    """
    if not _FPDF_OK:
        raise ImportError(
            "fpdf2 is required: pip install fpdf2"
        )

    os.makedirs(output_dir, exist_ok=True)
    key = _cache_key(questions, exam)

    if use_cache:
        cached = _cached_path(output_dir, key)
        if cached:
            return cached

    # ── Group by chapter ──────────────────────────────────────
    chapters: dict[str, list[dict]] = defaultdict(list)
    for q in questions:
        ch = q.get("chapter") or (q.get("subject") or "General").split("—")[-1].strip()
        chapters[ch].append(q)

    import datetime
    generated_str = datetime.datetime.utcnow().strftime("%d %B %Y, %H:%M UTC")

    # ── Build PDF ─────────────────────────────────────────────
    pdf = QuizForgePDF(exam=exam)
    pdf.set_title(f"QuizForge — {exam} Question Bank")
    pdf.set_author("QuizForge v3.0")
    pdf.set_creator("QuizForge")

    # Cover (page 1)
    pdf.cover_page(exam, len(questions), generated_str)

    # Questions — grouped by chapter
    q_num = 1
    chapter_q_map: dict[str, list[tuple[int, dict]]] = defaultdict(list)

    for chapter in sorted(chapters):
        pdf.add_page()
        pdf.chapter_heading(chapter, pdf.page_no())
        for q in chapters[chapter]:
            chapter_q_map[chapter].append((q_num, q))
            if q.get("type") == "numerical":
                pdf.render_numerical(q_num, q)
            else:
                pdf.render_mcq(q_num, q)
            q_num += 1

    # TOC — inserted at page 2 position after we know page numbers
    # (fpdf2 doesn't support page insertion, so we re-order via output tricks)
    # Simple approach: write TOC as page 2 using the _toc_entries built during rendering
    # We write it after questions but the reader sees it second via PDF metadata
    pdf.toc_page()

    # Answer key
    pdf.answer_key_page()

    out_path = os.path.join(output_dir, f"quizforge_{key}.pdf")
    try:
        pdf.output(out_path)
    except Exception as exc:
        raise RuntimeError(f"PDF write failed: {exc}") from exc

    return out_path


# ═══════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="QuizForge PDF Generator")
    parser.add_argument("--input",  default="pyq_full_database.json", help="JSON question bank")
    parser.add_argument("--exam",   default="ALL",  help="Exam filter: ALL|JEE|NEET|UPSC|CAT|SAT|GK")
    parser.add_argument("--output", default="pdfs", help="Output directory")
    parser.add_argument("--no-cache", action="store_true", help="Force regenerate")
    args = parser.parse_args()

    if not _FPDF_OK:
        print("❌ fpdf2 not installed.  Run:  pip install fpdf2")
        raise SystemExit(1)

    if not os.path.exists(args.input):
        print(f"❌ Input file not found: {args.input}")
        raise SystemExit(1)

    with open(args.input, encoding="utf-8") as f:
        all_questions = json.load(f)

    exam = args.exam.upper()
    if exam != "ALL":
        all_questions = [q for q in all_questions if q.get("exam", "").upper() == exam]

    if not all_questions:
        print(f"⚠️  No questions found for exam={exam}")
        raise SystemExit(0)

    print(f"\n🖨️  Generating PDF for {exam} ({len(all_questions)} questions)…")
    path = generate_pdf(all_questions, exam=exam, output_dir=args.output,
                        use_cache=not args.no_cache)
    print(f"✅ PDF saved → {path}\n")